tinyMCE.addI18n('es.fullpage_dlg',{
title:"Propiedades del documento",
meta_tab:"General",
appearance_tab:"Apariencia",
advanced_tab:"Avanzado",
meta_props:"Informacion Meta",
langprops:"Lenguaje y codificacion",
meta_title:"Titulo",
meta_keywords:"Palabras clave",
meta_description:"Descripcion",
meta_robots:"Robots",
doctypes:"Tipo de doc.",
langcode:"Codigo del lenguaje",
langdir:"Direccion del lenguaje",
ltr:"Izquierda a derecha",
rtl:"Derecha a izquierda",
xml_pi:"Declaracion XML",
encoding:"Codificacion de caracteres",
appearance_bgprops:"Propiedades del fondo",
appearance_marginprops:"Margenes",
appearance_linkprops:"Colores del vinculo",
appearance_textprops:"Propiedades de texto",
bgcolor:"Color de fondo",
bgimage:"Imagen de fondo",
left_margin:"Margen izquierdo",
right_margin:"Margen derecho",
top_margin:"Margen superior",
bottom_margin:"Margen inferior",
text_color:"Color del texto",
font_size:"Tamano de fuente",
font_face:"Fuente",
link_color:"Color de vinculo",
hover_color:"Color de Hover",
visited_color:"Color de visitado",
active_color:"Color de Activo",
textcolor:"Color",
fontsize:"Tamano de fuente",
fontface:"Fuente",
meta_index_follow:"Indexar y seguir los vinculos",
meta_index_nofollow:"Indexar y no seguir los vinculos",
meta_noindex_follow:"No indexar pero seguir vinculos",
meta_noindex_nofollow:"No indexar y no seguir vinculos",
appearance_style:"Propiedades de hoja de estilos y estilo",
stylesheet:"Hoja de estilo",
style:"Estilo",
author:"Autor",
copyright:"Copyright",
add:"Agregar nuevo elemento",
remove:"Eliminar elemento seleccionado",
moveup:"Mover elemento seleccionado hacia arriba",
movedown:"Mover elemento seleccionado hacia abajo",
head_elements:"Elemento Head",
info:"Informacion",
add_title:"Elemento Title",
add_meta:"Elemento Meta",
add_script:"Elemento Script",
add_style:"Elemento Style",
add_link:"Elemento Vinculo",
add_base:"Elemento Base",
add_comment:"Nodo Comment",
title_element:"Elemento Title",
script_element:"Elemento Script",
style_element:"Elemento Style",
base_element:"Elemento Base",
link_element:"Elemento Link",
meta_element:"Elemento Meta",
comment_element:"Comentario",
src:"Src",
language:"Lenguaje",
href:"Href",
target:"Target",
type:"Tipo",
charset:"Charset",
defer:"Defer",
media:"Medio",
properties:"Propiedades",
name:"Nombre",
value:"Valor",
content:"Contenido",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"General",
advanced_props:"Avanzado"
});