tinyMCE.addI18n('es.table_dlg',{
general_tab:"General",
advanced_tab:"Avanzado",
general_props:"Propiedades generales",
advanced_props:"Propiedades avanzadas",
rowtype:"Row in table part",
title:"Insertar/Modificar tabla",
width:"Ancho",
height:"Alto",
cols:"Cols",
rows:"Filas",
cellspacing:"Espaciado de celda",
cellpadding:"Relleno de celda",
border:"Borde",
align:"Alineacion",
align_default:"Default",
align_left:"Izquierda",
align_right:"Derecha",
align_middle:"Centro",
row_title:"Propiedades de la fila",
cell_title:"Propiedades de la celda",
cell_type:"Tipo de celda",
valign:"Alineacion vertical",
align_top:"Arriba",
align_bottom:"Debajo",
bordercolor:"Color del borde",
bgcolor:"Color de fondo",
merge_cells_title:"Vincular celdas",
id:"Id",
style:"Estilo",
langdir:"Direccion del lenguaje",
langcode:"Codigo del lenguaje",
mime:"Tipo MIME",
ltr:"Izquierda a derecha",
rtl:"Derecha a izquierda",
bgimage:"Imagen de fondo",
summary:"Resumen",
td:"Datos",
th:"Encabezado",
cell_cell:"Actualizar celda actual",
cell_row:"Actualizar todas las celdas en la fila",
cell_all:"Actualizar todas las celdas en la tabla",
row_row:"Actualizar fila actual",
row_odd:"Actualizar filas impares",
row_even:"Actualizar filas pares",
row_all:"Actualizar todas las filas",
thead:"Encabezado de la tabla",
tbody:"Cuerpo de la tabla",
tfoot:"Pie de la tabla",
scope:"Alcance",
rowgroup:"Grupo de filas",
colgroup:"Grupo de columnas",
col_limit:"Ud. ha superado el numero de columnas maximo de {$cols}.",
row_limit:"Ud. ha superado el numero de filas de {$rows}.",
cell_limit:"Ud. ha superado el numero de celdas de {$cells}.",
missing_scope:"Esta seguro que desea continuar sin especificar el alcance del encabezado de celda. Sin el, puede ser dificultoso para algunos usuarios centender el contenido o datos mostrados en la tabla.",
caption:"Subtitulo de la tabla",
frame:"Recuadro",
frame_none:"ninguno",
frame_groups:"grupos",
frame_rows:"filas",
frame_cols:"cols",
frame_all:"todos",
rules:"Rules",
rules_void:"void",
rules_above:"above",
rules_below:"below",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"box",
rules_border:"border"
});