<?php
/**
 * $Id$
 *
 * Used in conjunction with the navbar to create the north, west and north west payloads
 * and in doing so creating the webpage template. 
 *
 * Copyright (c) 2003 Jam Warehouse http://www.jamwarehouse.com under the GNU GPL.
 * See the file "docs/COPYING" for details
 *
 *
 * @version $Revision$
 * @author Brad Shuttleworth, Jam Warehouse (Pty) Ltd, South Africa
 */

require_once(KT_LIB_DIR . '/templating/kt3template.inc.php');

?>
