<?php

/*

  File: header.inc
  Author: Chris
  Date: 2000/12/14

  Owl: Copyright Chris Vincent <cvincent@project802.net>

  You should have received a copy of the GNU Public
  License along with this package; if not, write to the
  Free Software Foundation, Inc., 59 Temple Place - Suite 330,
  Boston, MA 02111-1307, USA.

*/

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
        "http://www.w3.org/TR/REC-html40/loose.dtd">
<HTML>
 <HEAD>
  <TITLE>Owl Intranet</TITLE>
<LINK REL="stylesheet" TYPE="text/css" TITLE="style1" HREF="<?php echo($default->styles)?>">
 </HEAD>

 <BODY BGCOLOR="<?php echo($default->body_bgcolor) ?>" 
          TEXT="<?php echo($default->body_textcolor) ?>" 
          LINK="<?php echo($default->body_link) ?>" 
         VLINK="<?php echo($default->body_vlink) ?>">
  <CENTER>
   <BR>
   <BR>
