<?php

//dashboard
$dashboard_welcome = "Hello {0}.  Welkom terug by die {1} DMS, deel van die Knowledge Tree";
$dashboard_archived_document_restoration_heading = "afr Archived Document Restoration Requests";
$dashboard_pending_documents_heading = "afr Pending Documents";
$dashboard_checked_out_documents_heading = "afr Checked Out Documents";
$dashboard_subscription_alerts_heading = "afr Subscription Alerts";
$dashboard_pending_documents_heading;
$dashboard_dependant_documents_heading = "afr Dependant Documents";
$dashboard_quick_links_heading = "afr Quick Links";

//browse
$browse_collection_heading = "afr Browse collection";

$browse_browse_type_category = "afr Category";

$browse_view_documents_by_heading = "afr View documents by";
$browse_view_documents_by_folder = "afr Folders";
$browse_view_documents_by_category = "afr Category";
$browse_view_documents_by_doctype = "afr Document Type";

$browse_folder_sort_title = "afr Title";
$browse_folder_sort_description = "afr Description";
$browse_folder_sort_creator = "afr Creator";
$browse_folder_sort_date_created = "afr Date Created";
$browse_folder_sort_document_type = "afr Document Type";

$browse_no_sub_folders = "afr This folder contains no sub folders";
$browse_no_documents = "afr This folder contains no documents";
$browse_no_document_permission = "afr You don't have access to the documents in this folder";


?>