<?php

//dashboard
$dashboard_welcome = "Hello {0}.  Welkom terug by die {1} DMS, deel van die Knowledge Tree";
$dashboard_archived_document_restoration_heading = "afr Archived Document Restoration Requests";
$dashboard_pending_documents_heading = "afr Pending Documents";
$dashboard_checked_out_documents_heading = "afr Checked Out Documents";
$dashboard_subscription_alerts_heading = "afr Subscription Alerts";
$dashboard_pending_documents_heading;
$dashboard_dependant_documents_heading = "afr Dependant Documents";
$dashboard_quick_links_heading = "afr Quick Links";

?>