<?php

//dashboard
$dashboard_welcome = "Hi {0}, welcome back to the {1} DMS, part of the Knowledge Tree";
$dashboard_archived_document_restoration_heading = "Archived Document Restoration Requests";
$dashboard_pending_documents_heading = "Pending Documents";
$dashboard_checked_out_documents_heading = "Checked Out Documents";
$dashboard_subscription_alerts_heading = "Subscription Alerts";
$dashboard_pending_documents_heading;
$dashboard_dependant_documents_heading = "Dependant Documents";
$dashboard_quick_links_heading = "Quick Links";

?>