<?php

//dashboard
$dashboard_welcome = "Hi {0}, welcome back to the {1} DMS, part of the Knowledge Tree";
$dashboard_archived_document_restoration_heading = "Archived Document Restoration Requests";
$dashboard_pending_documents_heading = "Pending Documents";
$dashboard_checked_out_documents_heading = "Checked Out Documents";
$dashboard_subscription_alerts_heading = "Subscription Alerts";
$dashboard_pending_documents_heading;
$dashboard_dependant_documents_heading = "Dependant Documents";
$dashboard_quick_links_heading = "Quick Links";

//browse
$browse_collection_heading = "Browse collection";
$browse_browse_type_category = "Category";

$browse_view_documents_by_heading = "View documents by";
$browse_view_documents_by_folder = "Folders";
$browse_view_documents_by_category = "Category";
$browse_view_documents_by_doctype = "Document Type";

$browse_folder_sort_title = "Title";
$browse_folder_sort_description = "Description";
$browse_folder_sort_creator = "Creator";
$browse_folder_sort_date_created = "Date Created";
$browse_folder_sort_document_type = "Document Type";

$browse_no_sub_folders = "This folder contains no sub folders";
$browse_no_documents = "This folder contains no documents";
$browse_no_document_permission = "You don't have access to the documents in this folder";

?>