tinyMCE.addI18n('es.style_dlg',{
title:"Editar Estilo CSS",
apply:"Aplicar",
text_tab:"Texto",
background_tab:"Fondo",
block_tab:"Bloque",
box_tab:"Caja",
border_tab:"Borde",
list_tab:"Lista",
positioning_tab:"Posicion",
text_props:"Texto",
text_font:"Fuente",
text_size:"Tama\u00F1o",
text_weight:"Espezor",
text_style:"Estilo",
text_variant:"Variante",
text_lineheight:"Ancho de la fila",
text_case:"Minus./Mayus.",
text_color:"Color",
text_decoration:"Decorativos",
text_overline:"overline",
text_underline:"subrayado",
text_striketrough:"tachado",
text_blink:"destello",
text_none:"ninguno",
background_color:"Color de fondo",
background_image:"Imagen de fondo",
background_repeat:"Repeticion",
background_attachment:"Adjunto",
background_hpos:"Posicion horizontal",
background_vpos:"Posicion vertical",
block_wordspacing:"Espacio entre palabra",
block_letterspacing:"Espacio entre letra",
block_vertical_alignment:"Alineacion vertical",
block_text_align:"Alineacion del texto",
block_text_indent:"Sangria",
block_whitespace:"Espacio en blanco",
block_display:"Display",
box_width:"Ancho",
box_height:"Alto",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"Lo mismo en todos",
top:"Arriba",
right:"Derecho",
bottom:"Debajo",
left:"Izquierdo",
margin:"Margen",
style:"Estilo",
width:"Ancho",
height:"Alto",
color:"Color",
list_type:"Tipo",
bullet_image:"Imagen de la vineta",
position:"Posicion",
positioning_type:"Tipo",
visibility:"Visibilidad",
zindex:"Z-index",
overflow:"Overflow",
placement:"Placement",
clip:"Clip"
});