ALTER TABLE active_sessions MODIFY session_id varbinary(255);
ALTER TABLE active_sessions MODIFY session_id char(255) CHARACTER SET utf8;
ALTER TABLE active_sessions MODIFY ip varbinary(30);
ALTER TABLE active_sessions MODIFY ip char(30) CHARACTER SET utf8;
ALTER TABLE archiving_type_lookup MODIFY name varbinary(100);
ALTER TABLE archiving_type_lookup MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE authentication_sources MODIFY name varbinary(50);
ALTER TABLE authentication_sources MODIFY name varchar(50) CHARACTER SET utf8;
ALTER TABLE authentication_sources MODIFY namespace varbinary(255);
ALTER TABLE authentication_sources MODIFY namespace varchar(255) CHARACTER SET utf8;
ALTER TABLE authentication_sources MODIFY authentication_provider varbinary(255);
ALTER TABLE authentication_sources MODIFY authentication_provider varchar(255) CHARACTER SET utf8;
ALTER TABLE authentication_sources MODIFY config blob;
ALTER TABLE authentication_sources MODIFY config text CHARACTER SET utf8;
ALTER TABLE `comment_searchable_text` DROP INDEX `comment_search_text`;
ALTER TABLE comment_searchable_text MODIFY body blob;
ALTER TABLE comment_searchable_text MODIFY body text CHARACTER SET utf8;
ALTER TABLE `comment_searchable_text` ADD FULLTEXT `comment_search_text` (`body`);
ALTER TABLE dashlet_disables MODIFY dashlet_namespace varbinary(255);
ALTER TABLE dashlet_disables MODIFY dashlet_namespace varchar(255) CHARACTER SET utf8;
ALTER TABLE data_types MODIFY name varbinary(255);
ALTER TABLE data_types MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE discussion_comments MODIFY subject blob;
ALTER TABLE discussion_comments MODIFY subject text CHARACTER SET utf8;
ALTER TABLE discussion_comments MODIFY body blob;
ALTER TABLE discussion_comments MODIFY body text CHARACTER SET utf8;
ALTER TABLE discussion_threads MODIFY close_reason blob;
ALTER TABLE discussion_threads MODIFY close_reason text CHARACTER SET utf8;
ALTER TABLE document_content_version MODIFY filename blob;
ALTER TABLE document_content_version MODIFY filename text CHARACTER SET utf8;
ALTER TABLE document_content_version MODIFY storage_path varbinary(250);
ALTER TABLE document_content_version MODIFY storage_path varchar(250) CHARACTER SET utf8;
ALTER TABLE document_fields MODIFY name varbinary(255);
ALTER TABLE document_fields MODIFY name varchar(255) CHARACTER SET utf8;
ALTER TABLE document_fields MODIFY data_type varbinary(100);
ALTER TABLE document_fields MODIFY data_type varchar(100) CHARACTER SET utf8;
ALTER TABLE document_fields MODIFY description blob;
ALTER TABLE document_fields MODIFY description text CHARACTER SET utf8;
ALTER TABLE document_fields_link MODIFY value varbinary(255);
ALTER TABLE document_fields_link MODIFY value char(255) CHARACTER SET utf8;
ALTER TABLE document_link_types MODIFY name varbinary(100);
ALTER TABLE document_link_types MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE document_link_types MODIFY reverse_name varbinary(100);
ALTER TABLE document_link_types MODIFY reverse_name char(100) CHARACTER SET utf8;
ALTER TABLE document_link_types MODIFY description varbinary(255);
ALTER TABLE document_link_types MODIFY description char(255) CHARACTER SET utf8;
ALTER TABLE document_metadata_version MODIFY name blob;
ALTER TABLE document_metadata_version MODIFY name text CHARACTER SET utf8;
ALTER TABLE document_metadata_version MODIFY description varbinary(200);
ALTER TABLE document_metadata_version MODIFY description varchar(200) CHARACTER SET utf8;
ALTER TABLE document_searchable_text DROP INDEX document_text;
ALTER TABLE document_searchable_text MODIFY document_text blob;
ALTER TABLE document_searchable_text MODIFY document_text text CHARACTER SET utf8;
ALTER TABLE document_searchable_text ADD FULLTEXT document_text (document_text);
ALTER TABLE document_text DROP INDEX document_text;
ALTER TABLE document_text MODIFY document_text blob;
ALTER TABLE document_text MODIFY document_text text CHARACTER SET utf8;
ALTER TABLE document_text ADD FULLTEXT document_text (document_text);
ALTER TABLE document_transaction_text DROP INDEX document_text;
ALTER TABLE document_transaction_text MODIFY document_text blob;
ALTER TABLE document_transaction_text MODIFY document_text text CHARACTER SET utf8;
ALTER TABLE document_transaction_text ADD FULLTEXT document_text (document_text);
ALTER TABLE document_transaction_types_lookup MODIFY name varbinary(100);
ALTER TABLE document_transaction_types_lookup MODIFY name varchar(100) CHARACTER SET utf8;
ALTER TABLE document_transaction_types_lookup MODIFY namespace varbinary(250);
ALTER TABLE document_transaction_types_lookup MODIFY namespace varchar(250) CHARACTER SET utf8;
ALTER TABLE document_transactions MODIFY version varbinary(50);
ALTER TABLE document_transactions MODIFY version char(50) CHARACTER SET utf8;
ALTER TABLE document_transactions MODIFY ip varbinary(30);
ALTER TABLE document_transactions MODIFY ip char(30) CHARACTER SET utf8;
ALTER TABLE document_transactions MODIFY filename varbinary(255);
ALTER TABLE document_transactions MODIFY filename char(255) CHARACTER SET utf8;
ALTER TABLE document_transactions MODIFY comment varbinary(255);
ALTER TABLE document_transactions MODIFY comment char(255) CHARACTER SET utf8;
ALTER TABLE document_transactions MODIFY transaction_namespace varbinary(255);
ALTER TABLE document_transactions MODIFY transaction_namespace char(255) CHARACTER SET utf8;
ALTER TABLE document_types_lookup MODIFY name varbinary(100);
ALTER TABLE document_types_lookup MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE documents MODIFY parent_folder_ids blob;
ALTER TABLE documents MODIFY parent_folder_ids text CHARACTER SET utf8;
ALTER TABLE documents MODIFY full_path blob;
ALTER TABLE documents MODIFY full_path text CHARACTER SET utf8;
ALTER TABLE field_behaviours MODIFY name varbinary(255);
ALTER TABLE field_behaviours MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE field_behaviours MODIFY human_name varbinary(100);
ALTER TABLE field_behaviours MODIFY human_name char(100) CHARACTER SET utf8;
ALTER TABLE fieldsets MODIFY name varbinary(255);
ALTER TABLE fieldsets MODIFY name varchar(255) CHARACTER SET utf8;
ALTER TABLE fieldsets MODIFY namespace varbinary(255);
ALTER TABLE fieldsets MODIFY namespace varchar(255) CHARACTER SET utf8;
ALTER TABLE fieldsets MODIFY description blob;
ALTER TABLE fieldsets MODIFY description text CHARACTER SET utf8;
ALTER TABLE folder_searchable_text DROP INDEX folder_text;
ALTER TABLE folder_searchable_text MODIFY folder_text blob;
ALTER TABLE folder_searchable_text MODIFY folder_text text CHARACTER SET utf8;
ALTER TABLE folder_searchable_text ADD FULLTEXT folder_text (folder_text);
ALTER TABLE folder_transactions MODIFY ip varbinary(30);
ALTER TABLE folder_transactions MODIFY ip char(30) CHARACTER SET utf8;
ALTER TABLE folder_transactions MODIFY comment varbinary(255);
ALTER TABLE folder_transactions MODIFY comment char(255) CHARACTER SET utf8;
ALTER TABLE folder_transactions MODIFY transaction_namespace varbinary(255);
ALTER TABLE folder_transactions MODIFY transaction_namespace char(255) CHARACTER SET utf8;
ALTER TABLE folders MODIFY name varbinary(255);
ALTER TABLE folders MODIFY name varchar(255) CHARACTER SET utf8;
ALTER TABLE folders MODIFY description varbinary(255);
ALTER TABLE folders MODIFY description varchar(255) CHARACTER SET utf8;
ALTER TABLE folders MODIFY parent_folder_ids blob;
ALTER TABLE folders MODIFY parent_folder_ids text CHARACTER SET utf8;
ALTER TABLE folders MODIFY full_path blob;
ALTER TABLE folders MODIFY full_path text CHARACTER SET utf8;
ALTER TABLE groups_lookup MODIFY name varbinary(100);
ALTER TABLE groups_lookup MODIFY name varchar(100) CHARACTER SET utf8;
ALTER TABLE groups_lookup MODIFY authentication_details_s2 varbinary(255);
ALTER TABLE groups_lookup MODIFY authentication_details_s2 varchar(255) CHARACTER SET utf8;
ALTER TABLE groups_lookup MODIFY authentication_details_s1 varbinary(255);
ALTER TABLE groups_lookup MODIFY authentication_details_s1 varchar(255) CHARACTER SET utf8;
ALTER TABLE help MODIFY fSection varbinary(100);
ALTER TABLE help MODIFY fSection varchar(100) CHARACTER SET utf8;
ALTER TABLE help MODIFY help_info blob;
ALTER TABLE help MODIFY help_info text CHARACTER SET utf8;
ALTER TABLE help_replacement MODIFY name varbinary(255);
ALTER TABLE help_replacement MODIFY name varchar(255) CHARACTER SET utf8;
ALTER TABLE help_replacement MODIFY description blob;
ALTER TABLE help_replacement MODIFY description text CHARACTER SET utf8;
ALTER TABLE help_replacement MODIFY title varbinary(255);
ALTER TABLE help_replacement MODIFY title varchar(255) CHARACTER SET utf8;
ALTER TABLE links MODIFY name varbinary(100);
ALTER TABLE links MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE links MODIFY url varbinary(100);
ALTER TABLE links MODIFY url char(100) CHARACTER SET utf8;
ALTER TABLE metadata_lookup MODIFY name varbinary(255);
ALTER TABLE metadata_lookup MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE metadata_lookup_tree MODIFY name varbinary(255);
ALTER TABLE metadata_lookup_tree MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE mime_types MODIFY filetypes varbinary(100);
ALTER TABLE mime_types MODIFY filetypes char(100) CHARACTER SET utf8;
ALTER TABLE mime_types MODIFY mimetypes varbinary(100);
ALTER TABLE mime_types MODIFY mimetypes char(100) CHARACTER SET utf8;
ALTER TABLE mime_types MODIFY icon_path varbinary(255);
ALTER TABLE mime_types MODIFY icon_path char(255) CHARACTER SET utf8;
ALTER TABLE mime_types MODIFY friendly_name varbinary(255);
ALTER TABLE mime_types MODIFY friendly_name char(255) CHARACTER SET utf8;
ALTER TABLE news MODIFY synopsis varbinary(255);
ALTER TABLE news MODIFY synopsis varchar(255) CHARACTER SET utf8;
ALTER TABLE news MODIFY body blob;
ALTER TABLE news MODIFY body text CHARACTER SET utf8;
ALTER TABLE news MODIFY image blob;
ALTER TABLE news MODIFY image text CHARACTER SET utf8;
ALTER TABLE notifications MODIFY label varbinary(255);
ALTER TABLE notifications MODIFY label varchar(255) CHARACTER SET utf8;
ALTER TABLE notifications MODIFY type varbinary(255);
ALTER TABLE notifications MODIFY type varchar(255) CHARACTER SET utf8;
ALTER TABLE notifications MODIFY data_str_1 varbinary(255);
ALTER TABLE notifications MODIFY data_str_1 varchar(255) CHARACTER SET utf8;
ALTER TABLE notifications MODIFY data_str_2 varbinary(255);
ALTER TABLE notifications MODIFY data_str_2 varchar(255) CHARACTER SET utf8;
ALTER TABLE organisations_lookup MODIFY name varbinary(100);
ALTER TABLE organisations_lookup MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE permission_descriptors MODIFY descriptor varbinary(32);
ALTER TABLE permission_descriptors MODIFY descriptor varchar(32) CHARACTER SET utf8;
ALTER TABLE permission_descriptors MODIFY descriptor_text blob;
ALTER TABLE permission_descriptors MODIFY descriptor_text text CHARACTER SET utf8;
ALTER TABLE permissions MODIFY name varbinary(100);
ALTER TABLE permissions MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE permissions MODIFY human_name varbinary(100);
ALTER TABLE permissions MODIFY human_name char(100) CHARACTER SET utf8;
ALTER TABLE plugins MODIFY namespace varbinary(255);
ALTER TABLE plugins MODIFY namespace varchar(255) CHARACTER SET utf8;
ALTER TABLE plugins MODIFY path varbinary(255);
ALTER TABLE plugins MODIFY path varchar(255) CHARACTER SET utf8;
ALTER TABLE plugins MODIFY data blob;
ALTER TABLE plugins MODIFY data text CHARACTER SET utf8;
ALTER TABLE plugins MODIFY friendly_name varbinary(255);
ALTER TABLE plugins MODIFY friendly_name varchar(255) CHARACTER SET utf8;
ALTER TABLE roles MODIFY name varbinary(255);
ALTER TABLE roles MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE saved_searches MODIFY name varbinary(50);
ALTER TABLE saved_searches MODIFY name varchar(50) CHARACTER SET utf8;
ALTER TABLE saved_searches MODIFY namespace varbinary(250);
ALTER TABLE saved_searches MODIFY namespace varchar(250) CHARACTER SET utf8;
ALTER TABLE saved_searches MODIFY search blob;
ALTER TABLE saved_searches MODIFY search text CHARACTER SET utf8;
ALTER TABLE status_lookup MODIFY name varbinary(255);
ALTER TABLE status_lookup MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE system_settings MODIFY name varbinary(255);
ALTER TABLE system_settings MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE system_settings MODIFY value varbinary(255);
ALTER TABLE system_settings MODIFY value char(255) CHARACTER SET utf8;
ALTER TABLE time_unit_lookup MODIFY name varbinary(100);
ALTER TABLE time_unit_lookup MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE trigger_selection MODIFY event_ns varbinary(255);
ALTER TABLE trigger_selection MODIFY event_ns varchar(255) CHARACTER SET utf8;
ALTER TABLE trigger_selection MODIFY selection_ns varbinary(255);
ALTER TABLE trigger_selection MODIFY selection_ns varchar(255) CHARACTER SET utf8;
ALTER TABLE units_lookup MODIFY name varbinary(100);
ALTER TABLE units_lookup MODIFY name char(100) CHARACTER SET utf8;
ALTER TABLE upgrades MODIFY descriptor varbinary(100);
ALTER TABLE upgrades MODIFY descriptor char(100) CHARACTER SET utf8;
ALTER TABLE upgrades MODIFY description varbinary(255);
ALTER TABLE upgrades MODIFY description char(255) CHARACTER SET utf8;
ALTER TABLE upgrades MODIFY parent varbinary(40);
ALTER TABLE upgrades MODIFY parent char(40) CHARACTER SET utf8;
ALTER TABLE user_history MODIFY action_namespace varbinary(255);
ALTER TABLE user_history MODIFY action_namespace varchar(255) CHARACTER SET utf8;
ALTER TABLE user_history MODIFY comments blob;
ALTER TABLE user_history MODIFY comments text CHARACTER SET utf8;
ALTER TABLE users MODIFY username varbinary(255);
ALTER TABLE users MODIFY username varchar(255) CHARACTER SET utf8;
ALTER TABLE users MODIFY name varbinary(255);
ALTER TABLE users MODIFY name varchar(255) CHARACTER SET utf8;
ALTER TABLE users MODIFY password varbinary(255);
ALTER TABLE users MODIFY password varchar(255) CHARACTER SET utf8;
ALTER TABLE users MODIFY email varbinary(255);
ALTER TABLE users MODIFY email varchar(255) CHARACTER SET utf8;
ALTER TABLE users MODIFY mobile varbinary(255);
ALTER TABLE users MODIFY mobile varchar(255) CHARACTER SET utf8;
ALTER TABLE users MODIFY authentication_details_s1 varbinary(255);
ALTER TABLE users MODIFY authentication_details_s1 varchar(255) CHARACTER SET utf8;
ALTER TABLE users MODIFY authentication_details_s2 varbinary(255);
ALTER TABLE users MODIFY authentication_details_s2 varchar(255) CHARACTER SET utf8;
ALTER TABLE workflow_actions MODIFY action_name varbinary(255);
ALTER TABLE workflow_actions MODIFY action_name char(255) CHARACTER SET utf8;
ALTER TABLE workflow_state_actions MODIFY action_name varbinary(255);
ALTER TABLE workflow_state_actions MODIFY action_name char(255) CHARACTER SET utf8;
ALTER TABLE workflow_states MODIFY name varbinary(255);
ALTER TABLE workflow_states MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE workflow_states MODIFY human_name varbinary(100);
ALTER TABLE workflow_states MODIFY human_name char(100) CHARACTER SET utf8;
ALTER TABLE workflow_transitions MODIFY name varbinary(255);
ALTER TABLE workflow_transitions MODIFY name char(255) CHARACTER SET utf8;
ALTER TABLE workflow_transitions MODIFY human_name varbinary(100);
ALTER TABLE workflow_transitions MODIFY human_name char(100) CHARACTER SET utf8;
ALTER TABLE workflows MODIFY name varbinary(250);
ALTER TABLE workflows MODIFY name char(250) CHARACTER SET utf8;
ALTER TABLE workflows MODIFY human_name varbinary(100);
ALTER TABLE workflows MODIFY human_name char(100) CHARACTER SET utf8;
