#!/bin/sh
# git-rbranch

if [ $# -ne 1 ]; then
    echo 1>&2 Usage: $0 branch_name
    exit 127
fi

branch_name=$1

check_return() {
	if [ $1 -ne 0 ] ; then
		exit $1
	fi
}

if [ -n "$(git branch |egrep "^[[:space:]*]*${branch_name}\$")" ] ; then
    echo "Local branch already exists, cannot continue"
    exit 1
fi

if [ -n "$(git branch -r |egrep "^[[:space:]*]*${branch_name}\$")" ] ; then
	echo "Remote branch already exists, checking out"
	git checkout --track -b ${branch_name} origin/${branch_name}
	check_return $?
	git pull
	check_return $?
	exit 0
fi

git checkout -b $1
git push origin $1 && git config branch.$1.remote origin && git config branch.$1.merge refs/heads/$1
